### ISSUE TITLE
URLが消えています

### ISSUE THREAD

**Issue by katoken-0215** [anydown/maildown#2]
https://anydown.github.io/maildown/ の文例で、

> ソースはGitHub上にアップロード致しました。ご確認下さい。
> https://github.com/anydown/maildown

のURL箇所が消えているように見えます。

Firefox 52.0.2, Google Chrome 57.0.2987.133 で再現しました。

**Comment by katoken-0215** [comment]
![2017-05-02 10 30 59](https://cloud.githubusercontent.com/assets/532265/25600893/813ba806-2f22-11e7-991d-173cf556223e.png)

**Comment by hashrock** [comment]
いつもお世話になっております。

大変申し訳ございません。現象を確認いたしました。
リンクだけではなく、多くのインライン要素が消えてしまっています。

気が向いた時に修正させて頂きます。
ご迷惑をおかけしており、大変申し訳ございません。

以上、何卒よろしくお願いいたします。

**Comment by hashrock** [comment]
450e204892dfd0f18f88812ab7ccff6c67782844

**Comment by hashrock** [comment]
本件、対応いたしました。ご査収ください。
ご連絡ありがとうございました。

**Comment by katoken-0215** [comment]
👍
