### ISSUE TITLE
">" による引用が出来ません

### ISSUE THREAD

**Issue by 82p** [anydown/maildown#3]
いつもお世話になっております。

標題の通りなのですが、`>`による引用ができません。
日本の一般的なメールでも `>` が引用の意味であることは明白ですので、そのまま表示させても構わないのではないかと存じます。

 以上ご検討よろしくお願い致します。

**Comment by 82p** [comment]
お世話になっております。

差し出がましいと思いましたがプルリクエストをさせていただきます。

#4  BlockQuoteの件

初めてのプルリクエストで不手際ございましたら申し訳ございません。

以上、ご精査願います。

**Comment by hashrock** [comment]
いつもお世話になっております。

変更内容、Issueの文面も含め、パーフェクトです。
プルリクエスト取り込ませて頂きました。
後ほどDEMOにも反映させていただきます。

他にお気づきの点などございましたら、ご連絡ください。
今後とも弊社をよろしくお願いいたします。
以上、何卒よろしくお願いいたします。
