### ISSUE TITLE
区切り線の種類につきまして

### ISSUE THREAD

**Issue by 82p** [anydown/maildown#5]
お世話になっております。 @82p でございます。

貴社の ｍａｉｌｄｏｗｎ につきましては、いつも大変便利に利用いたしております。
大変恐縮ではございますが一つ提案がございます。

ハイフンを利用した区切り線につきまして、 [ＲＣ３６７６](http://www.ietf.org/rfc/rfc3676.txt) にありますように
ハイフンには本文と書名を分ける意味がございます。

つきましては、

================================================

などの記号に変更できますでしょうか。

個人的な趣味の範囲かとも思いますが以上よろしくお願い致します。

**Comment by hashrock** [comment]
毎々お世話になっております。@hashrock です。

一点ご確認させて下さい。
ｈｒタグ（ｍａｒｋｄｏｗｎでは---）を
コンバート後の文字列を===などに変更する、
ということでよろしかったでしょうか。

ＲＣ３６７６の件、大変勉強になります。
ほかにもお気づきの点がございましたら、
どしどしご指摘を頂けますと幸いです。

以上、何卒よろしくお願い致します。

**Comment by hashrock** [comment]
対応が大変遅くなり申し訳ございません。
区切り文字を変更いたしました。
以上、何卒宜しくお願いします。
