### ISSUE TITLE
リストの改行につきまして

### ISSUE THREAD

**Issue by 82p** [anydown/maildown#6]
お世話になっております。重ね重ね申し訳ございません。

リストの改行についても30文字で改行するようにと、弊社上長より指摘を受けました。

```
入力
* そもそもリストに３０文字以上の文をいれるのがナンセンスなのかもしれませんが対応していただけると嬉しいです。

出力
　・そもそもリストに３０文字以上の文をいれるのがナンセンスなのかもしれ
　　ませんが対応していただけると嬉しいです。
```

こちらも対応ただければ幸いです。

何卒宜しくお願い致します。

**Comment by hashrock** [comment]
お世話になっております。

本件承知いたしました。
可能かどうか、開発担当に確認したいので、一旦本社に持ち帰らせて下さい。
開発の目処が立ち次第、ご連絡させて頂きます。よろしくお願い致します。

**Comment by hashrock** [comment]
![2018-07-22 15 26 45](https://user-images.githubusercontent.com/3132889/43043024-dc51aee6-8dc4-11e8-8b91-9b03283b9c32.png)

対応が大変遅くなり申し訳ございません。
開発担当が外出していたため、対応が遅れてしまいました。
本日、対応版の冶具をリリースさせていただきました。
以上、何卒よろしくお願いいたします。
